version: '3'
volumes:
  php-fpm-socket:
  mongo-db:
  mongo-configdb:
networks:
  todo-stack:
services:
  frontend:
    image: ghcr.io/himantyu-yuma/todo-stack/todo-stack_frontend:latest
    ports:
      - 3000:3000
    environment:
      BACKEND_SCHEME: http
      BACKEND_HOST:
  web:
    image: ghcr.io/himantyu-yuma/todo-stack/todo-stack_web:latest
    ports:
      - 80:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    networks:
      - todo-stack
  app:
    image: ghcr.io/himantyu-yuma/todo-stack/todo-stack_app:latest
    ports:
      - 8080:8080
    volumes:
      - php-fpm-socket:/var/run/php-fpm
    networks:
      - todo-stack
    environment:
      TZ: Asia/Tokyo
      LOG_CHANNEL: stderr
      LOG_LEVEL: info
      DB_CONNECTION: mongodb
      APP_DEBUG: 0
      MONGO_DB_HOST:
      MONGO_DB_DATABASE:
      MONGO_DB_USERNAME:
      MONGO_DB_PASSWORD:
  db:
    image: todo-stack_db:latest
    restart: always
    environment:
      TZ: Asia/Tokyo
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE:
    ports:
      - 27017:27017
    networks:
      - todo-stack
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb
  db-admin:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - todo-stack
    environment:
      ME_CONFIG_MONGODB_SERVER:
      ME_CONFIG_MONGODB_ADMINUSERNAME:
      ME_CONFIG_MONGODB_ADMINPASSWORD:
