name: Build and Push for GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_PREFIX: todo-stack_

jobs:
  push_backend:
    name: Push backend docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [web, app]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate image ID
        run: |
          IMAGE_ID=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          tags: ${{ env.IMAGE_ID }}
          context: ./backend
          file: ./backend/docker/${{ matrix.image }}/Dockerfile
          target: production
          push: true

  push_frontend:
    name: Push frontend docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [frontend]
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Generate image ID
        run: |
          IMAGE_ID=${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ env.DOCKER_IMAGE_PREFIX }}${{ matrix.image }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          tags: ${{ env.IMAGE_ID }}
          context: ./frontend
          file: ./frontend/Dockerfile
          target: production
          push: true
